### ISSUE TITLE
the `download` example includes `-R` but there doesn't seem to be an `-R` flag

### ISSUE THREAD

**Issue by jhrozek** [github-early-access/gh-attestation#2]
This might be just me being thick but the `gh attestation download` example includes an `-R` flag:
```
Examples:

# Download attestations for an artifact using the associated GitHub owner/organization and repository
$ gh attestation download <artifact-path-or-url> -R <owner/repo>
```

but that doesn't seem to work and is not listed in the list of flags further on:
```
Flags:
  -d, --digest-alg string   The algorithm used to compute a digest of the artifact (sha256 or sha512) (default "sha256")
  -h, --help                help for download
  -L, --limit int           Maximum number of attestations to fetch (default 30)
  -o, --owner string        a GitHub organization to scope attestation lookup by
  -v, --verbose             If set to true, the CLI will output verbose information.
```

Any chance the example uses a flag that's no longer present?

(I did not find the source for the plugin, the repo seems to only include the `tuf` directory, so I apologise if this issue is less useful than it should be)

**Comment by malancas** [comment]
The `download` command does not support the `--repo` flag. It only supports the `--owner` flag. I'll update the example to reflect this. Thanks for filing this issue!

**Comment by malancas** [comment]
Closing this issue for now as the incorrect example has been removed in the newest release [v0.2.3](https://github.com/github-early-access/gh-attestation/releases/tag/v0.2.3).
